<a href="https://colab.research.google.com/github/GauravKr10/DMDW-LAB/blob/main/ASSIGNMENT%20-2%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10 MOST USED COMMAND IN NUMPY

# Array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# Empty()

In [3]:
e = np.empty([2,2])
print(e)

[[1. 1.]
 [1. 0.]]


# Zeros()

In [4]:
b = np.zeros(2, dtype = int)
print(b)

[0 0]


# ones()

In [5]:
b = np.ones([2,2], dtype = int)
print(b)

[[1 1]
 [1 1]]


# vstack()

In [10]:
x = np.array([ 3,5,7] )
print ("1st Input array : \n", x) 
  
y = np.array([ 5,7,9] )
print ("2nd Input array : \n", y) 

z = np.vstack((x,y))
print ("Output vertically stacked array:\n ", z)

1st Input array : 
 [3 5 7]
2nd Input array : 
 [5 7 9]
Output vertically stacked array:
  [[3 5 7]
 [5 7 9]]


# hstack()

In [11]:
x = np.array([ 3,5,7] )
print ("1st Input array : \n", x) 
  
y = np.array([ 5,7,9] )
print ("2nd Input array : \n", y) 

z = np.hstack((x,y))
print ("Output vertically stacked array:\n ", z)

1st Input array : 
 [3 5 7]
2nd Input array : 
 [5 7 9]
Output vertically stacked array:
  [3 5 7 5 7 9]


# indexing()

In [12]:
a = np.array([1,2,3,6,9])
print(a[1])

2


# slicing

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


# shape()

In [20]:
import numpy as np
a = np.array([[1,2,3] , [5,6,7]])
print(a.shape)

(2, 3)


# reshape()

In [26]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newy = x.reshape(2, 4)

print(newy)

[[1 2 3 4]
 [5 6 7 8]]


# broadcast()

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a*b
print (c)

[ 4 10 18]


# Execute 5 most used command in pandas

# dataframe()

In [31]:
import pandas as pd

In [33]:


lst = [1,2,3]

df = pd.DataFrame(lst)
print(df)

   0
0  1
1  2
2  3


# head()

In [37]:
df = pd.DataFrame({'animal':['snake', 'bat', 'tiger', 'lion',
                   'fox', 'eagle', 'shark', 'dog', 'deer']})
df
df.head(3)

animal
0  snake
1    bat
2  tiger

# loc()


In [42]:
import pandas as pd
df = pd.DataFrame({'Weight':[45, 88, 56, 15, 71],
                   'Name':['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'],
                   'Age':[14, 25, 55, 8, 21]})
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']
  
df.index = index_
  
print(df)
result = df.loc['Row_2', 'Name']
print(result)

       Weight    Name  Age
Row_1      45     Sam   14
Row_2      88  Andrea   25
Row_3      56    Alex   55
Row_4      15   Robin    8
Row_5      71     Kia   21
Andrea
