<a href="https://colab.research.google.com/github/GauravKr10/DMDW-LAB/blob/main/ASSIGNMENT-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

10 MOST USED COMMAND IN NUMPY

1. Array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


2. Empty()

In [3]:
e = np.empty([2,2])
print(e)

[[1. 1.]
 [1. 0.]]


3. Zeros()

In [4]:
b = np.zeros(2, dtype = int)
print(b)

[0 0]


4. ones()

In [5]:
b = np.ones([2,2], dtype = int)
print(b)

[[1 1]
 [1 1]]


5. vstack()

In [10]:
x = np.array([ 3,5,7] )
print ("1st Input array : \n", x) 
  
y = np.array([ 5,7,9] )
print ("2nd Input array : \n", y) 

z = np.vstack((x,y))
print ("Output vertically stacked array:\n ", z)

1st Input array : 
 [3 5 7]
2nd Input array : 
 [5 7 9]
Output vertically stacked array:
  [[3 5 7]
 [5 7 9]]


6. hstack()

In [11]:
x = np.array([ 3,5,7] )
print ("1st Input array : \n", x) 
  
y = np.array([ 5,7,9] )
print ("2nd Input array : \n", y) 

z = np.hstack((x,y))
print ("Output vertically stacked array:\n ", z)

1st Input array : 
 [3 5 7]
2nd Input array : 
 [5 7 9]
Output vertically stacked array:
  [3 5 7 5 7 9]


7. indexing()

In [12]:
a = np.array([1,2,3,6,9])
print(a[1])

2


8. slicing

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


9. shape()

In [20]:
import numpy as np
a = np.array([[1,2,3] , [5,6,7]])
print(a.shape)

(2, 3)


10. reshape()

In [26]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newy = x.reshape(2, 4)

print(newy)

[[1 2 3 4]
 [5 6 7 8]]


10. broadcast()

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a*b
print (c)

[ 4 10 18]
